---
name: GCC 10
on:
        push:
        schedule:
                - cron: '0 0 * * 0'
        pull_request:
jobs:
        gcc-10:
                name: Build & Test
                runs-on: ubuntu-latest
                container: archlinux:latest
                steps:
                        - name: Setup
                          run: |
                                pacman -Sy base-devel git gtest dtc libtommath wget --noconfirm
                                wget https://aur.archlinux.org/cgit/aur.git/snapshot/libtomcrypt.tar.gz
                                tar xf libtomcrypt.tar.gz
                                cd libtomcrypt
                                sed -i 's/check()/dont_check()/' PKGBUILD
                                runuser nobody makepkg
                                pacman -U --noconfirm libtomcrypt*.pkg.tar.xz
                        - name: Clone
                          uses: actions/checkout@v2
                        - name: Test
                          run: make check
